# Configuration for the data ingestion pipeline

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion    # Root directory for all data ingestion artifacts
  source_URL: https://github.com/yatheeshpateel/Insurence_prediction_with_MLpipeline/raw/refs/heads/main/insurance.zip  # URL of the zipped data source
  local_data_file: artifacts/data_ingestion/data.zip # Path to store the downloaded zip file
  raw_data_dir: artifacts/data_ingestion/data        # Directory to store the extracted raw data
  unzip_dir: artifacts/data_ingestion/data        # Directory where the zip file will be extracted (same as raw_data_dir)


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data/insurance.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data/insurance.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json